<?php /** @var $block \SP\Events\Block\EventList */ ?>
<h1><?php echo __('Latest Events Data') ?></h1>
<ul class="blog-post-list">
    <?php /** @var $event \SP\Events\Model\Event */ ?>
    <?php foreach ($this->getEvents() as $event): ?>
        <li class="blog-post-list-item">
            <h3 class="blog-post-item-title">
                <a href="#"><?php echo $event->getTitle() ?></a>
            </h3>

            <div class="blog-post-item-content">
                <?php echo $event->getShortDescription(); ?>
            </div>

            <div class="blog-post-item-meta">
                <strong><?php echo __('Display from:') ?></strong> <?php echo $event->getDisplayFrom(); ?>
            </div>
        </li>
    <?php endforeach; ?>
</ul>