<?php
/**
 * @author Pavel Usachev <webcodekeeper@hotmail.com>
 * @copyright Copyright (c) 2017, Pavel Usachev
 */

namespace SP\Slider\Model\Session;

use  Magento\Catalog\Model\Session;

class Proxy extends Session
{
    public function start()
    {
        return parent::start(); // TODO: Change the autogenerated stub
    }
}