<?php
/**
 * @author Pavel Usachev <webcodekeeper@hotmail.com>
 * @copyright Copyright (c) 2017, Pavel Usachev
 */

namespace MageNet\SimpleSlider\Controller\Adminhtml\Slider;

use MageNet\SimpleSlider\Controller\Adminhtml\Slider as BaseAction;

class Index extends BaseAction
{
    const ACL_RESOURCE      = 'MageNet_SimpleSlider::grid';
    const MENU_ITEM         = 'MageNet_SimpleSlider::grid';
    const PAGE_TITLE        = 'Slider Grid';
    const BREADCRUMB_TITLE  = 'Slider Grid';

    public function execute()
    {
        return parent::execute(); // TODO: Change the autogenerated stub
    }
}
